var constants = {};

constants.MONSTER = {};

constants.MONSTER.TYPE = {
    ALBATROS: {
        KEY: 'ALBATROS',
        NAME: 'Albatros'
    },
    ANT: {
        KEY: 'ANT',
        NAME: 'Ant'
    },
    BULL: {
        KEY: 'BULL',
        NAME: 'Bull'
    },
    CONDOR: {
        KEY: 'CONDOR',
        NAME: 'Condor'
    },
    CRAB: {
        KEY: 'CRAB',
        NAME: 'Crab'
    },
    DRAGON: {
        KEY: 'DRAGON',
        NAME: 'Dragon'
    },
    EYE: {
        KEY: 'EYE',
        NAME: 'Eye'
    },
    FIEND: {
        KEY: 'FIEND',
        NAME: 'Fiend'
    },
    FISH: {
        KEY: 'FISH',
        NAME: 'Fish'
    },
    FLY: {
        KEY: 'FLY',
        NAME: 'Fly'
    },
    GHOST: {
        KEY: 'GHOST',
        NAME: 'Ghost'
    },
    GOBLIN: {
        KEY: 'GOBLIN',
        NAME: 'Goblin'
    },
    GOLEM: {
        KEY: 'GOLEM',
        NAME: 'Golem'
    },
    GRIFFIN: {
        KEY: 'GRIFFIN',
        NAME: 'Griffin'
    },
    IMP: {
        KEY: 'IMP',
        NAME: 'Imp'
    },
    LIZARD: {
        KEY: 'LIZARD',
        NAME: 'Lizard'
    },
    MEDUSA: {
        KEY: 'MEDUSA',
        NAME: 'Medusa'
    },
    PLANT: {
        KEY: 'PLANT',
        NAME: 'Plant'
    },
    RAT: {
        KEY: 'RAT',
        NAME: 'Rat'
    },
    SEA: {
        KEY: 'SEA',
        NAME: 'Sea Creature'
    },
    SKELETON: {
        KEY: 'SKELETON',
        NAME: 'Skeleton'
    },
    SLIME: {
        KEY: 'SLIME',
        NAME: 'Slime'
    },
    SNAKE: {
        KEY: 'SNAKE',
        NAME: 'Snake'
    },
    WOLF: {
        KEY: 'WOLF',
        NAME: 'Wolf'
    },
    WORM: {
        KEY: 'WORM',
        NAME: 'Worm'
    },
    ZOMBIE: {
        KEY: 'ZOMBIE',
        NAME: 'Zombie'
    }
};

constants.MONSTER.TRANSFORMATION_TYPE = {
    ALBATROS:  {
        KEY: constants.MONSTER.TYPE.ALBATROS.KEY
    },
    ANT:  {
        KEY: constants.MONSTER.TYPE.ANT.KEY
    },
    BULL:  {
        KEY: constants.MONSTER.TYPE.BULL.KEY
    },
    CONDOR:  {
        KEY: constants.MONSTER.TYPE.CONDOR.KEY
    },
    CRAB:  {
        KEY: constants.MONSTER.TYPE.CRAB.KEY
    },
    DRAGON:  {
        KEY: constants.MONSTER.TYPE.DRAGON.KEY
    },
    EYE:  {
        KEY: constants.MONSTER.TYPE.EYE.KEY
    },
    FISH:  {
        KEY: constants.MONSTER.TYPE.FISH.KEY
    },
    FLY:  {
        KEY: constants.MONSTER.TYPE.FLY.KEY
    },
    GHOST:  {
        KEY: constants.MONSTER.TYPE.GHOST.KEY
    },
    GOBLIN:  {
        KEY: constants.MONSTER.TYPE.GOBLIN.KEY
    },
    GOLEM:  {
        KEY: constants.MONSTER.TYPE.GOLEM.KEY
    },
    GRIFFIN:  {
        KEY: constants.MONSTER.TYPE.GRIFFIN.KEY
    },
    IMP:  {
        KEY: constants.MONSTER.TYPE.IMP.KEY
    },
    LIZARD:  {
        KEY: constants.MONSTER.TYPE.LIZARD.KEY
    },
    MEDUSA:  {
        KEY: constants.MONSTER.TYPE.MEDUSA.KEY
    },
    PLANT:  {
        KEY: constants.MONSTER.TYPE.PLANT.KEY
    },
    RAT:  {
        KEY: constants.MONSTER.TYPE.RAT.KEY
    },
    SEA:  {
        KEY: constants.MONSTER.TYPE.SEA.KEY
    },
    SKELETON:  {
        KEY: constants.MONSTER.TYPE.SKELETON.KEY
    },
    SLIME:  {
        KEY: constants.MONSTER.TYPE.SLIME.KEY
    },
    SNAKE:  {
        KEY: constants.MONSTER.TYPE.SNAKE.KEY
    },
    WOLF:  {
        KEY: constants.MONSTER.TYPE.WOLF.KEY
    },
    WORM:  {
        KEY: constants.MONSTER.TYPE.WORM.KEY
    },
    ZOMBIE:  {
        KEY: constants.MONSTER.TYPE.ZOMBIE.KEY
    },
    GEN_BU:  {
        KEY: 'GEN_BU'
    },
    SEI_RYU:  {
        KEY: 'SEI_RYU'
    },
    BYAK_KO:  {
        KEY: 'BYAK_KO'
    },
    SU_ZAKU:  {
        KEY: 'SU_ZAKU'
    },
};

constants.MONSTER.TRANSFORMATION_GROUP = {
    ALBATROS_DRAGON_GRIFFIN: {
        KEY: 'ALBATROS_DRAGON_GRIFFIN'
    },
    ANT_FLY_CRAB: {
        KEY: 'ANT_FLY_CRAB'
    },
    BULL_LIZARD: {
        KEY: 'BULL_LIZARD'
    },
    CONDOR_IMP: {
        KEY: 'CONDOR_IMP'
    },
    EYE_SLIME: {
        KEY: 'EYE_SLIME'
    },
    FISH: {
        KEY: 'FISH'
    },
    GHOST_SKELETON_ZOMBIE: {
        KEY: 'GHOST_SKELETON_ZOMBIE'
    },
    GOBLIN_RAT_WOLF: {
        KEY: 'GOBLIN_RAT_WOLF'
    },
    GOLEM: {
        KEY: 'GOLEM'
    },
    MEDUSA_SNAKE_WORM: {
        KEY: 'MEDUSA_SNAKE_WORM'
    },
    PLANT_SEA: {
        KEY: 'PLANT_SEA'
    }
};

constants.MONSTER.TRANSFORMATION = {
    ALBATROS_DRAGON_GRIFFIN: {
        ALBATROS: null,
        ANT: constants.MONSTER.TYPE.BULL.KEY,
        BULL: constants.MONSTER.TYPE.SLIME.KEY,
        CONDOR: constants.MONSTER.TYPE.FISH.KEY,
        CRAB: constants.MONSTER.TYPE.EYE.KEY,
        DRAGON: null,
        EYE: constants.MONSTER.TYPE.CRAB.KEY,
        FISH: null,
        FLY: constants.MONSTER.TYPE.ALBATROS.KEY,
        GHOST: constants.MONSTER.TYPE.ZOMBIE.KEY,
        GOBLIN: constants.MONSTER.TYPE.SKELETON.KEY,
        GOLEM: constants.MONSTER.TYPE.SEA.KEY,
        GRIFFIN: null,
        IMP: constants.MONSTER.TYPE.WORM.KEY,
        LIZARD: constants.MONSTER.TYPE.GOBLIN.KEY,
        MEDUSA: constants.MONSTER.TYPE.GOLEM.KEY,
        PLANT: constants.MONSTER.TYPE.GRIFFIN.KEY,
        RAT: constants.MONSTER.TYPE.FLY.KEY,
        SEA: constants.MONSTER.TYPE.CONDOR.KEY,
        SKELETON: constants.MONSTER.TYPE.LIZARD.KEY,
        SLIME: constants.MONSTER.TYPE.ANT.KEY,
        SNAKE: constants.MONSTER.TYPE.GHOST.KEY,
        WOLF: constants.MONSTER.TYPE.SNAKE.KEY,
        WORM: constants.MONSTER.TYPE.WOLF.KEY,
        ZOMBIE: constants.MONSTER.TYPE.RAT.KEY,
        GEN_BU: constants.MONSTER.TYPE.IMP.KEY,
        SEI_RYU: constants.MONSTER.TYPE.DRAGON.KEY,
        BYAK_KO: constants.MONSTER.TYPE.DRAGON.KEY,
        SU_ZAKU: constants.MONSTER.TYPE.MEDUSA.KEY
    },
    ANT_FLY_CRAB: {
        ALBATROS: constants.MONSTER.TYPE.ANT.KEY,
        ANT: null,
        BULL: constants.MONSTER.TYPE.LIZARD.KEY,
        CONDOR: constants.MONSTER.TYPE.SLIME.KEY,
        CRAB: null,
        DRAGON: constants.MONSTER.TYPE.CONDOR.KEY,
        EYE: constants.MONSTER.TYPE.IMP.KEY,
        FISH: constants.MONSTER.TYPE.FLY.KEY,
        FLY: null,
        GHOST: constants.MONSTER.TYPE.SKELETON.KEY,
        GOBLIN: constants.MONSTER.TYPE.GHOST.KEY,
        GOLEM: constants.MONSTER.TYPE.GRIFFIN.KEY,
        GRIFFIN: constants.MONSTER.TYPE.PLANT.KEY,
        IMP: constants.MONSTER.TYPE.WOLF.KEY,
        LIZARD: constants.MONSTER.TYPE.RAT.KEY,
        MEDUSA: constants.MONSTER.TYPE.SEA.KEY,
        PLANT: constants.MONSTER.TYPE.EYE.KEY,
        RAT: constants.MONSTER.TYPE.ZOMBIE.KEY,
        SEA: constants.MONSTER.TYPE.WORM.KEY,
        SKELETON: null,
        SLIME: constants.MONSTER.TYPE.ALBATROS.KEY,
        SNAKE: constants.MONSTER.TYPE.BULL.KEY,
        WOLF: constants.MONSTER.TYPE.FISH.KEY,
        WORM: constants.MONSTER.TYPE.SNAKE.KEY,
        ZOMBIE: constants.MONSTER.TYPE.GOBLIN.KEY,
        GEN_BU: constants.MONSTER.TYPE.DRAGON.KEY,
        SEI_RYU: constants.MONSTER.TYPE.GOLEM.KEY,
        BYAK_KO: constants.MONSTER.TYPE.GOLEM.KEY,
        SU_ZAKU: constants.MONSTER.TYPE.MEDUSA.KEY
    },
    BULL_LIZARD: {
        ALBATROS: null,
        ANT: constants.MONSTER.TYPE.LIZARD.KEY,
        BULL: null,
        CONDOR: constants.MONSTER.TYPE.IMP.KEY,
        CRAB: constants.MONSTER.TYPE.WORM.KEY,
        DRAGON: constants.MONSTER.TYPE.SEA.KEY,
        EYE: constants.MONSTER.TYPE.SNAKE.KEY,
        FISH: constants.MONSTER.TYPE.BULL.KEY,
        FLY: constants.MONSTER.TYPE.ANT.KEY,
        GHOST: constants.MONSTER.TYPE.FLY.KEY,
        GOBLIN: constants.MONSTER.TYPE.ALBATROS.KEY,
        GOLEM: constants.MONSTER.TYPE.MEDUSA.KEY,
        GRIFFIN: constants.MONSTER.TYPE.CONDOR.KEY,
        IMP: constants.MONSTER.TYPE.GHOST.KEY,
        LIZARD: null,
        MEDUSA: constants.MONSTER.TYPE.EYE.KEY,
        PLANT: constants.MONSTER.TYPE.CRAB.KEY,
        RAT: null,
        SEA: constants.MONSTER.TYPE.WOLF.KEY,
        SKELETON: constants.MONSTER.TYPE.GOBLIN.KEY,
        SLIME: constants.MONSTER.TYPE.ZOMBIE.KEY,
        SNAKE: constants.MONSTER.TYPE.FISH.KEY,
        WOLF: constants.MONSTER.TYPE.RAT.KEY,
        WORM: constants.MONSTER.TYPE.SLIME.KEY,
        ZOMBIE: constants.MONSTER.TYPE.SKELETON.KEY,
        GEN_BU: constants.MONSTER.TYPE.PLANT.KEY,
        SEI_RYU: constants.MONSTER.TYPE.GOLEM.KEY,
        BYAK_KO: constants.MONSTER.TYPE.GOLEM.KEY,
        SU_ZAKU: constants.MONSTER.TYPE.GRIFFIN.KEY
    },
    CONDOR_IMP: {
        ALBATROS: constants.MONSTER.TYPE.GHOST.KEY,
        ANT: constants.MONSTER.TYPE.WORM.KEY,
        BULL: null,
        CONDOR: null,
        CRAB: constants.MONSTER.TYPE.SKELETON.KEY,
        DRAGON: constants.MONSTER.TYPE.CRAB.KEY,
        EYE: constants.MONSTER.TYPE.RAT.KEY,
        FISH: constants.MONSTER.TYPE.CONDOR.KEY,
        FLY: constants.MONSTER.TYPE.BULL.KEY,
        GHOST: constants.MONSTER.TYPE.ALBATROS.KEY,
        GOBLIN: constants.MONSTER.TYPE.IMP.KEY,
        GOLEM: constants.MONSTER.TYPE.MEDUSA.KEY,
        GRIFFIN: constants.MONSTER.TYPE.PLANT.KEY,
        IMP: null,
        LIZARD: null,
        MEDUSA: constants.MONSTER.TYPE.GOLEM.KEY,
        PLANT: constants.MONSTER.TYPE.FISH.KEY,
        RAT: constants.MONSTER.TYPE.WOLF.KEY,
        SEA: constants.MONSTER.TYPE.FLY.KEY,
        SKELETON: constants.MONSTER.TYPE.ANT.KEY,
        SLIME: constants.MONSTER.TYPE.SNAKE.KEY,
        SNAKE: constants.MONSTER.TYPE.ZOMBIE.KEY,
        WOLF: constants.MONSTER.TYPE.LIZARD.KEY,
        WORM: constants.MONSTER.TYPE.GOBLIN.KEY,
        ZOMBIE: constants.MONSTER.TYPE.SLIME.KEY,
        GEN_BU: constants.MONSTER.TYPE.EYE.KEY,
        SEI_RYU: constants.MONSTER.TYPE.EYE.KEY,
        BYAK_KO: constants.MONSTER.TYPE.EYE.KEY,
        SU_ZAKU: constants.MONSTER.TYPE.SEA.KEY
    },
    EYE_SLIME: {
        ALBATROS: constants.MONSTER.TYPE.BULL.KEY,
        ANT: constants.MONSTER.TYPE.ALBATROS.KEY,
        BULL: constants.MONSTER.TYPE.SKELETON.KEY,
        CONDOR: constants.MONSTER.TYPE.WORM.KEY,
        CRAB: constants.MONSTER.TYPE.SEA.KEY,
        DRAGON: constants.MONSTER.TYPE.MEDUSA.KEY,
        EYE: null,
        FISH: constants.MONSTER.TYPE.WOLF.KEY,
        FLY: null,
        GHOST: constants.MONSTER.TYPE.GHOST.KEY,
        GOBLIN: constants.MONSTER.TYPE.RAT.KEY,
        GOLEM: constants.MONSTER.TYPE.EYE.KEY,
        GRIFFIN: constants.MONSTER.TYPE.SEA.KEY,
        IMP: constants.MONSTER.TYPE.SNAKE.KEY,
        LIZARD: constants.MONSTER.TYPE.ANT.KEY,
        MEDUSA: constants.MONSTER.TYPE.CRAB.KEY,
        PLANT: constants.MONSTER.TYPE.CONDOR.KEY,
        RAT: constants.MONSTER.TYPE.GHOST.KEY,
        SEA: constants.MONSTER.TYPE.FISH.KEY,
        SKELETON: constants.MONSTER.TYPE.ZOMBIE.KEY,
        SLIME: null,
        SNAKE: null,
        WOLF: constants.MONSTER.TYPE.SLIME.KEY,
        WORM: constants.MONSTER.TYPE.FLY.KEY,
        ZOMBIE: constants.MONSTER.TYPE.LIZARD.KEY,
        GEN_BU: constants.MONSTER.TYPE.GRIFFIN.KEY,
        SEI_RYU: constants.MONSTER.TYPE.PLANT.KEY,
        BYAK_KO: constants.MONSTER.TYPE.PLANT.KEY,
        SU_ZAKU: constants.MONSTER.TYPE.DRAGON.KEY
    },
    FISH: {
        ALBATROS: constants.MONSTER.TYPE.SNAKE.KEY,
        ANT: null,
        BULL: constants.MONSTER.TYPE.WOLF.KEY,
        CONDOR: constants.MONSTER.TYPE.ALBATROS.KEY,
        CRAB: constants.MONSTER.TYPE.CONDOR.KEY,
        DRAGON: constants.MONSTER.TYPE.EYE.KEY,
        EYE: constants.MONSTER.TYPE.SEA.KEY,
        FISH: null,
        FLY: constants.MONSTER.TYPE.GOBLIN.KEY,
        GHOST: constants.MONSTER.TYPE.RAT.KEY,
        GOBLIN: null,
        GOLEM: constants.MONSTER.TYPE.PLANT.KEY,
        GRIFFIN: constants.MONSTER.TYPE.CRAB.KEY,
        IMP: constants.MONSTER.TYPE.ZOMBIE.KEY,
        LIZARD: constants.MONSTER.TYPE.BULL.KEY,
        MEDUSA: constants.MONSTER.TYPE.IMP.KEY,
        PLANT: constants.MONSTER.TYPE.GHOST.KEY,
        RAT: constants.MONSTER.TYPE.SKELETON.KEY,
        SEA: constants.MONSTER.TYPE.SLIME.KEY,
        SKELETON: constants.MONSTER.TYPE.FLY.KEY,
        SLIME: constants.MONSTER.TYPE.ANT.KEY,
        SNAKE: constants.MONSTER.TYPE.LIZARD.KEY,
        WOLF: null,
        WORM: constants.MONSTER.TYPE.FISH.KEY,
        ZOMBIE: constants.MONSTER.TYPE.WORM.KEY,
        GEN_BU: constants.MONSTER.TYPE.MEDUSA.KEY,
        SEI_RYU: constants.MONSTER.TYPE.DRAGON.KEY,
        BYAK_KO: constants.MONSTER.TYPE.DRAGON.KEY,
        SU_ZAKU: constants.MONSTER.TYPE.GOLEM.KEY
    },
    GHOST_SKELETON_ZOMBIE: {
        ALBATROS: constants.MONSTER.TYPE.GOBLIN.KEY,
        ANT: constants.MONSTER.TYPE.SKELETON.KEY,
        BULL: constants.MONSTER.TYPE.FLY.KEY,
        CONDOR: constants.MONSTER.TYPE.SNAKE.KEY,
        CRAB: constants.MONSTER.TYPE.WOLF.KEY,
        DRAGON: constants.MONSTER.TYPE.GRIFFIN.KEY,
        EYE: constants.MONSTER.TYPE.CONDOR.KEY,
        FISH: constants.MONSTER.TYPE.WORM.KEY,
        FLY: constants.MONSTER.TYPE.RAT.KEY,
        GHOST: null,
        GOBLIN: constants.MONSTER.TYPE.LIZARD.KEY,
        GOLEM: null,
        GRIFFIN: constants.MONSTER.TYPE.EYE.KEY,
        IMP: constants.MONSTER.TYPE.ANT.KEY,
        LIZARD: constants.MONSTER.TYPE.ALBATROS.KEY,
        MEDUSA: constants.MONSTER.TYPE.PLANT.KEY,
        PLANT: constants.MONSTER.TYPE.IMP.KEY,
        RAT: constants.MONSTER.TYPE.BULL.KEY,
        SEA: constants.MONSTER.TYPE.CRAB.KEY,
        SKELETON: null,
        SLIME: constants.MONSTER.TYPE.GHOST.KEY,
        SNAKE: constants.MONSTER.TYPE.SLIME.KEY,
        WOLF: constants.MONSTER.TYPE.ZOMBIE.KEY,
        WORM: constants.MONSTER.TYPE.FISH.KEY,
        ZOMBIE: null,
        GEN_BU: constants.MONSTER.TYPE.SEA.KEY,
        SEI_RYU: constants.MONSTER.TYPE.MEDUSA.KEY,
        BYAK_KO: constants.MONSTER.TYPE.MEDUSA.KEY,
        SU_ZAKU: constants.MONSTER.TYPE.GOLEM.KEY
    },
    GOBLIN_RAT_WOLF: {
        ALBATROS: constants.MONSTER.TYPE.LIZARD.KEY,
        ANT: constants.MONSTER.TYPE.FLY.KEY,
        BULL: constants.MONSTER.TYPE.RAT.KEY,
        CONDOR: constants.MONSTER.TYPE.WOLF.KEY,
        CRAB: constants.MONSTER.TYPE.BULL.KEY,
        DRAGON: constants.MONSTER.TYPE.PLANT.KEY,
        EYE: constants.MONSTER.TYPE.FISH.KEY,
        FISH: constants.MONSTER.TYPE.GOBLIN.KEY,
        FLY: constants.MONSTER.TYPE.ZOMBIE.KEY,
        GHOST: constants.MONSTER.TYPE.SLIME.KEY,
        GOBLIN: null,
        GOLEM: constants.MONSTER.TYPE.CRAB.KEY,
        GRIFFIN: constants.MONSTER.TYPE.SNAKE.KEY,
        IMP: constants.MONSTER.TYPE.CONDOR.KEY,
        LIZARD: constants.MONSTER.TYPE.SKELETON.KEY,
        MEDUSA: constants.MONSTER.TYPE.GRIFFIN.KEY,
        PLANT: constants.MONSTER.TYPE.SEA.KEY,
        RAT: null,
        SEA: constants.MONSTER.TYPE.IMP.KEY,
        SKELETON: constants.MONSTER.TYPE.ALBATROS.KEY,
        SLIME: null,
        SNAKE: constants.MONSTER.TYPE.WORM.KEY,
        WOLF: null,
        WORM: constants.MONSTER.TYPE.ANT.KEY,
        ZOMBIE: constants.MONSTER.TYPE.GHOST.KEY,
        GEN_BU: constants.MONSTER.TYPE.GOLEM.KEY,
        SEI_RYU: constants.MONSTER.TYPE.MEDUSA.KEY,
        BYAK_KO: constants.MONSTER.TYPE.MEDUSA.KEY,
        SU_ZAKU: constants.MONSTER.TYPE.DRAGON.KEY
    },
    GOLEM: {
        ALBATROS: constants.MONSTER.TYPE.CONDOR.KEY,
        ANT: constants.MONSTER.TYPE.EYE.KEY,
        BULL: constants.MONSTER.TYPE.SNAKE.KEY,
        CONDOR: constants.MONSTER.TYPE.FLY.KEY,
        CRAB: null,
        DRAGON: constants.MONSTER.TYPE.BULL.KEY,
        EYE: constants.MONSTER.TYPE.SLIME.KEY,
        FISH: constants.MONSTER.TYPE.SKELETON.KEY,
        FLY: constants.MONSTER.TYPE.IMP.KEY,
        GHOST: constants.MONSTER.TYPE.LIZARD.KEY,
        GOBLIN: constants.MONSTER.TYPE.MEDUSA.KEY,
        GOLEM: null,
        GRIFFIN: null,
        IMP: constants.MONSTER.TYPE.ALBATROS.KEY,
        LIZARD: constants.MONSTER.TYPE.GRIFFIN.KEY,
        MEDUSA: null,
        PLANT: constants.MONSTER.TYPE.ANT.KEY,
        RAT: constants.MONSTER.TYPE.WORM.KEY,
        SEA: constants.MONSTER.TYPE.ZOMBIE.KEY,
        SKELETON: constants.MONSTER.TYPE.CRAB.KEY,
        SLIME: constants.MONSTER.TYPE.PLANT.KEY,
        SNAKE: constants.MONSTER.TYPE.GOLEM.KEY,
        WOLF: constants.MONSTER.TYPE.GOBLIN.KEY,
        WORM: constants.MONSTER.TYPE.SEA.KEY,
        ZOMBIE: constants.MONSTER.TYPE.WOLF.KEY,
        GEN_BU: constants.MONSTER.TYPE.GHOST.KEY,
        SEI_RYU: constants.MONSTER.TYPE.DRAGON.KEY,
        BYAK_KO: constants.MONSTER.TYPE.DRAGON.KEY,
        SU_ZAKU: constants.MONSTER.TYPE.FISH.KEY
    },
    MEDUSA_SNAKE_WORM: {
        ALBATROS: constants.MONSTER.TYPE.WORM.KEY,
        ANT: constants.MONSTER.TYPE.SNAKE.KEY,
        BULL: constants.MONSTER.TYPE.ALBATROS.KEY,
        CONDOR: constants.MONSTER.TYPE.IMP.KEY,
        CRAB: constants.MONSTER.TYPE.IMP.KEY,
        DRAGON: constants.MONSTER.TYPE.GOLEM.KEY,
        EYE: null,
        FISH: constants.MONSTER.TYPE.LIZARD.KEY,
        FLY: constants.MONSTER.TYPE.SLIME.KEY,
        GHOST: constants.MONSTER.TYPE.ANT.KEY,
        GOBLIN: constants.MONSTER.TYPE.BULL.KEY,
        GOLEM: constants.MONSTER.TYPE.CONDOR.KEY,
        GRIFFIN: constants.MONSTER.TYPE.SEA.KEY,
        IMP: constants.MONSTER.TYPE.SKELETON.KEY,
        LIZARD: constants.MONSTER.TYPE.WOLF.KEY,
        MEDUSA: null,
        PLANT: constants.MONSTER.TYPE.CRAB.KEY,
        RAT: constants.MONSTER.TYPE.GOBLIN.KEY,
        SEA: constants.MONSTER.TYPE.EYE.KEY,
        SKELETON: constants.MONSTER.TYPE.RAT.KEY,
        SLIME: constants.MONSTER.TYPE.FISH.KEY,
        SNAKE: null,
        WOLF: constants.MONSTER.TYPE.GHOST.KEY,
        WORM: null,
        ZOMBIE: constants.MONSTER.TYPE.FLY.KEY,
        GEN_BU: constants.MONSTER.TYPE.DRAGON.KEY,
        SEI_RYU: constants.MONSTER.TYPE.GRIFFIN.KEY,
        BYAK_KO: constants.MONSTER.TYPE.GRIFFIN.KEY,
        SU_ZAKU: constants.MONSTER.TYPE.PLANT.KEY
    },
    PLANT_SEA: {
        ALBATROS: constants.MONSTER.TYPE.IMP.KEY,
        ANT: constants.MONSTER.TYPE.SLIME.KEY,
        BULL: constants.MONSTER.TYPE.GOBLIN.KEY,
        CONDOR: null,
        CRAB: constants.MONSTER.TYPE.FLY.KEY,
        DRAGON: constants.MONSTER.TYPE.MEDUSA.KEY,
        EYE: constants.MONSTER.TYPE.ANT.KEY,
        FISH: constants.MONSTER.TYPE.SEA.KEY,
        FLY: constants.MONSTER.TYPE.CONDOR.KEY,
        GHOST: constants.MONSTER.TYPE.BULL.KEY,
        GOBLIN: constants.MONSTER.TYPE.EYE.KEY,
        GOLEM: constants.MONSTER.TYPE.GHOST.KEY,
        GRIFFIN: constants.MONSTER.TYPE.WOLF.KEY,
        IMP: null,
        LIZARD: constants.MONSTER.TYPE.CRAB.KEY,
        MEDUSA: constants.MONSTER.TYPE.SKELETON.KEY,
        PLANT: null,
        RAT: constants.MONSTER.TYPE.LIZARD.KEY,
        SEA: null,
        SKELETON: constants.MONSTER.TYPE.SNAKE.KEY,
        SLIME: constants.MONSTER.TYPE.WORM.KEY,
        SNAKE: constants.MONSTER.TYPE.RAT.KEY,
        WOLF: constants.MONSTER.TYPE.ALBATROS.KEY,
        WORM: constants.MONSTER.TYPE.ZOMBIE.KEY,
        ZOMBIE: constants.MONSTER.TYPE.FISH.KEY,
        GEN_BU: constants.MONSTER.TYPE.GOLEM.KEY,
        SEI_RYU: constants.MONSTER.TYPE.PLANT.KEY,
        BYAK_KO: constants.MONSTER.TYPE.PLANT.KEY,
        SU_ZAKU: constants.MONSTER.TYPE.DRAGON.KEY
    }
};

constants.MONSTERS = [
    {
        agility: 9,
        defense: 3,
        hp: 20,
        level: 1,
        mana: 4,
        name: 'Albatros',
        strength: 6,
        image: { height: 192, width: 144, x: -360, y: -423 },
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.ALBATROS.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ALBATROS.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 38,
        defense: 14,
        hp: 150,
        level: 6,
        mana: 21,
        name: 'Eagle',
        strength: 23,
        image: { height: 192, width: 144, x: -360, y: -423},
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.ALBATROS.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ALBATROS.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 74,
        defense: 32,
        hp: 330,
        level: 10,
        mana: 45,
        name: 'Thunder',
        strength: 47,
        image: { height: 192, width: 144, x: -360, y: -423},
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.ALBATROS.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ALBATROS.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 99,
        defense: 47,
        hp: 501,
        level: 12,
        mana: 64,
        name: 'Cocatris',
        strength: 66,
        image: { height: 192, width: 144, x: -360, y: -423},
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.ALBATROS.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ALBATROS.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 99,
        defense: 56,
        hp: 606,
        level: 13,
        mana: 74,
        name: 'Rock',
        strength: 76,
        image: { height: 192, width: 144, x: -360, y: -423},
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.ALBATROS.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ALBATROS.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 99,
        defense: 62,
        hp: 666,
        level: 16,
        mana: 80,
        name: 'Phoenix',
        strength: 82,
        image: { height: 192, width: 144, x: -360, y: -423},
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.ALBATROS.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ALBATROS.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 7,
        defense: 9,
        hp: 20,
        level: 1,
        mana: 6,
        name: 'Clipper',
        strength: 4,
        image: { height: 192, width: 96, x: -18, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.ANT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ANT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 38,
        defense: 40,
        hp: 202,
        level: 7,
        mana: 29,
        name: 'Beetle',
        strength: 19,
        image: { height: 192, width: 96, x: -18, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.ANT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ANT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 43,
        defense: 45,
        hp: 231,
        level: 8,
        mana: 33,
        name: 'Ant Lion',
        strength: 22,
        image: { height: 192, width: 96, x: -18, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.ANT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ANT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 53,
        defense: 55,
        hp: 295,
        level: 9,
        mana: 41,
        name: 'Atom Ant',
        strength: 28,
        image: { height: 192, width: 96, x: -18, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.ANT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ANT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 87,
        defense: 89,
        hp: 551,
        level: 13,
        mana: 70,
        name: 'Scorpion',
        strength: 52,
        image: { height: 192, width: 96, x: -18, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.ANT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ANT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 99,
        defense: 99,
        hp: 666,
        level: 16,
        mana: 81,
        name: 'Scarab',
        strength: 62,
        image: { height: 192, width: 96, x: -18, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.ANT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ANT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 5,
        defense: 7,
        hp: 60,
        level: 1,
        mana: 4,
        name: 'Redbull',
        strength: 8,
        image: { height: 192, width: 141, x: -1623, y: -192},
        avatar: { height: 32, width: 32, x: -992, y: -638 },
        type: constants.MONSTER.TYPE.BULL.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.BULL.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.BULL_LIZARD.KEY
    }, {
        agility: 14,
        defense: 16,
        hp: 150,
        level: 4,
        mana: 9,
        name: 'Rhino',
        strength: 21,
        image: { height: 192, width: 141, x: -1623, y: -192},
        avatar: { height: 32, width: 32, x: -992, y: -638 },
        type: constants.MONSTER.TYPE.BULL.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.BULL.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.BULL_LIZARD.KEY
    }, {
        agility: 36,
        defense: 38,
        hp: 295,
        level: 8,
        mana: 25,
        name: 'Triceras',
        strength: 49,
        image: { height: 192, width: 141, x: -1623, y: -192},
        avatar: { height: 32, width: 32, x: -992, y: -638 },
        type: constants.MONSTER.TYPE.BULL.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.BULL.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.BULL_LIZARD.KEY
    }, {
        agility: 45,
        defense: 47,
        hp: 409,
        level: 10,
        mana: 32,
        name: 'Behemoth',
        strength: 60,
        image: { height: 192, width: 141, x: -1623, y: -192},
        avatar: { height: 32, width: 32, x: -992, y: -638 },
        type: constants.MONSTER.TYPE.BULL.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.BULL.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.BULL_LIZARD.KEY
    }, {
        agility: 69,
        defense: 71,
        hp: 666,
        level: 13,
        mana: 52,
        name: 'Baku',
        strength: 88,
        image: { height: 192, width: 141, x: -1623, y: -192},
        avatar: { height: 32, width: 32, x: -992, y: -638 },
        type: constants.MONSTER.TYPE.BULL.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.BULL.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.BULL_LIZARD.KEY
    }, {
        agility: 80,
        defense: 82,
        hp: 795,
        level: 16,
        mana: 62,
        name: 'Ganesha',
        strength: 99,
        image: { height: 192, width: 141, x: -1623, y: -192},
        avatar: { height: 32, width: 32, x: -992, y: -638 },
        type: constants.MONSTER.TYPE.BULL.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.BULL.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.BULL_LIZARD.KEY
    }, {
        agility: 14,
        defense: 6,
        hp: 82,
        level: 3,
        mana: 9,
        name: 'Condor',
        strength: 11,
        image: { height: 192, width: 96, x: -1053, y: 0},
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.CONDOR.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.CONDOR.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.CONDOR_IMP.KEY
    }, {
        agility: 25,
        defense: 11,
        hp: 150,
        level: 5,
        mana: 17,
        name: 'Raven',
        strength: 19,
        image: { height: 192, width: 96, x: -1053, y: 0},
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.CONDOR.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.CONDOR.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.CONDOR_IMP.KEY
    }, {
        agility: 39,
        defense: 19,
        hp: 231,
        level: 7,
        mana: 28,
        name: 'Harpy',
        strength: 30,
        image: { height: 192, width: 96, x: -1053, y: 0},
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.CONDOR.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.CONDOR.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.CONDOR_IMP.KEY
    }, {
        agility: 60,
        defense: 32,
        hp: 368,
        level: 10,
        mana: 45,
        name: 'Ten-gu',
        strength: 47,
        image: { height: 192, width: 96, x: -1053, y: 0},
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.CONDOR.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.CONDOR.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.CONDOR_IMP.KEY
    }, {
        agility: 88,
        defense: 52,
        hp: 606,
        level: 13,
        mana: 69,
        name: 'Garuda',
        strength: 71,
        image: { height: 192, width: 96, x: -1053, y: 0},
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.CONDOR.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.CONDOR.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.CONDOR_IMP.KEY
    }, {
        agility: 99,
        defense: 62,
        hp: 729,
        level: 16,
        mana: 80,
        name: 'Nike',
        strength: 82,
        image: { height: 192, width: 96, x: -1053, y: 0},
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.CONDOR.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.CONDOR.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.CONDOR_IMP.KEY
    }, {
        agility: 8,
        defense: 22,
        hp: 103,
        level: 4,
        mana: 6,
        name: 'Shrimp',
        strength: 13,
        image: { height: 192, width: 96, x: -156, y: -192},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.CRAB.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.CRAB.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 12,
        defense: 32,
        hp: 150,
        level: 5,
        mana: 10,
        name: 'Atomcrab',
        strength: 18,
        image: { height: 192, width: 96, x: -156, y: -192},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.CRAB.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.CRAB.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 26,
        defense: 61,
        hp: 295,
        level: 8,
        mana: 24,
        name: 'Crab',
        strength: 37,
        image: { height: 192, width: 96, x: -156, y: -192},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.CRAB.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.CRAB.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 29,
        defense: 67,
        hp: 330,
        level: 9,
        mana: 27,
        name: 'Ice Crab',
        strength: 41,
        image: { height: 192, width: 96, x: -156, y: -192},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.CRAB.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.CRAB.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 53,
        defense: 99,
        hp: 606,
        level: 13,
        mana: 51,
        name: 'Kingcrab',
        strength: 70,
        image: { height: 192, width: 96, x: -156, y: -192},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.CRAB.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.CRAB.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 63,
        defense: 99,
        hp: 729,
        level: 16,
        mana: 61,
        name: 'Dagon',
        strength: 81,
        image: { height: 192, width: 96, x: -156, y: -192},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.CRAB.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.CRAB.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 19,
        defense: 28,
        hp: 202,
        level: 7,
        mana: 39,
        name: 'Dragon 1',
        strength: 30,
        image: { height: 192, width: 140, x: -180, y: -423},
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.DRAGON.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.DRAGON.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 25,
        defense: 36,
        hp: 262,
        level: 8,
        mana: 49,
        name: 'Dragon 2',
        strength: 38,
        image: { height: 192, width: 140, x: -180, y: -423},
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.DRAGON.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.DRAGON.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 35,
        defense: 49,
        hp: 368,
        level: 10,
        mana: 65,
        name: 'Dragon 3',
        strength: 51,
        image: { height: 192, width: 140, x: -180, y: -423},
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.DRAGON.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.DRAGON.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 47,
        defense: 64,
        hp: 501,
        level: 12,
        mana: 83,
        name: 'Dragon 4',
        strength: 66,
        image: { height: 192, width: 140, x: -180, y: -423},
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.DRAGON.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.DRAGON.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 56,
        defense: 74,
        hp: 606,
        level: 13,
        mana: 94,
        name: 'Dragon 5',
        strength: 76,
        image: { height: 192, width: 140, x: -180, y: -423},
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.DRAGON.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.DRAGON.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 62,
        defense: 80,
        hp: 666,
        level: 16,
        mana: 99,
        name: 'Tiamat',
        strength: 99,
        image: { height: 192, width: 140, x: -180, y: -423},
        avatar: { height: 32, width: 32, x: -202, y: -638 },
        type: constants.MONSTER.TYPE.DRAGON.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.DRAGON.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 6,
        defense: 12,
        hp: 82,
        level: 4,
        mana: 22,
        name: 'Big Eye',
        strength: 8,
        image: { height: 192, width: 72, x: -288, y: 0},
        avatar: { height: 32, width: 32, x: -792, y: -638 },
        type: constants.MONSTER.TYPE.EYE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.EYE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.EYE_SLIME.KEY
    }, {
        agility: 18,
        defense: 29,
        hp: 202,
        level: 7,
        mana: 49,
        name: 'Gazer',
        strength: 20,
        image: { height: 192, width: 72, x: -288, y: 0},
        avatar: { height: 32, width: 32, x: -792, y: -638 },
        type: constants.MONSTER.TYPE.EYE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.EYE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.EYE_SLIME.KEY
    }, {
        agility: 27,
        defense: 41,
        hp: 295,
        level: 9,
        mana: 67,
        name: 'Seeker',
        strength: 29,
        image: { height: 192, width: 72, x: -288, y: 0},
        avatar: { height: 32, width: 32, x: -792, y: -638 },
        type: constants.MONSTER.TYPE.EYE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.EYE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.EYE_SLIME.KEY
    }, {
        agility: 42,
        defense: 60,
        hp: 454,
        level: 12,
        mana: 94,
        name: 'Watcher',
        strength: 44,
        image: { height: 192, width: 72, x: -288, y: 0},
        avatar: { height: 32, width: 32, x: -792, y: -638 },
        type: constants.MONSTER.TYPE.EYE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.EYE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.EYE_SLIME.KEY
    }, {
        agility: 55,
        defense: 75,
        hp: 606,
        level: 13,
        mana: 99,
        name: 'Evil Eye',
        strength: 57,
        image: { height: 192, width: 72, x: -288, y: 0},
        avatar: { height: 32, width: 32, x: -792, y: -638 },
        type: constants.MONSTER.TYPE.EYE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.EYE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.EYE_SLIME.KEY
    }, {
        agility: 61,
        defense: 81,
        hp: 666,
        level: 16,
        mana: 99,
        name: 'Beholder',
        strength: 63,
        image: { height: 192, width: 72, x: -288, y: 0},
        avatar: { height: 32, width: 32, x: -792, y: -638 },
        type: constants.MONSTER.TYPE.EYE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.EYE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.EYE_SLIME.KEY
    }, {
        agility: 12,
        defense: 11,
        hp: 250,
        level: null,
        mana: 12,
        name: 'Gen-bu',
        strength: 12,
        image: { height: 192, width: 144, x: -903, y: -423},
        avatar: { height: 64, width: 64, x: -162, y: -476 },
        type: constants.MONSTER.TYPE.FIEND.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GEN_BU.KEY,
        transformationGroup: null
    }, {
        agility: 27,
        defense: 25,
        hp: 600,
        level: 7,
        mana: 27,
        name: 'Sei-ryu',
        strength: 27,
        image: { height: 192, width: 144, x: -1098, y: -423},
        avatar: { height: 64, width: 64, x: -252, y: -476 },
        type: constants.MONSTER.TYPE.FIEND.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SEI_RYU.KEY,
        transformationGroup: null
    }, {
        agility: 50,
        defense: 45,
        hp: 1000,
        level: null,
        mana: 50,
        name: 'Byak-ko',
        strength: 50,
        image: { height: 192, width: 144, x: -1293, y: -423},
        avatar: { height: 64, width: 64, x: -432, y: -476 },
        type: constants.MONSTER.TYPE.FIEND.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.BYAK_KO.KEY,
        transformationGroup: null
    }, {
        agility: 85,
        defense: 77,
        hp:  1500,
        level: 13,
        mana: 85,
        name: 'Su-zaku',
        strength: 85,
        image: { height: 192, width: 141, x: -1488, y: -423},
        avatar: { height: 64, width: 96, x: -522, y: -476 },
        type: constants.MONSTER.TYPE.FIEND.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SU_ZAKU.KEY,
        transformationGroup: null
    }, {
        agility: 90,
        defense: 100,
        hp: 1500,
        level: 16,
        mana: 90,
        name: 'Gen-bu2',
        strength: 90,
        image: { height: 192, width: 144, x: -903, y: -423},
        avatar: { height: 64, width: 64, x: -162, y: -476 },
        type: constants.MONSTER.TYPE.FIEND.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GEN_BU.KEY,
        transformationGroup: null
    }, {
        agility: 90,
        defense: 90,
        hp: 1750,
        level: 16,
        mana: 100,
        name: 'Sei-ryu2',
        strength: 100,
        image: { height: 192, width: 144, x: -1098, y: -423},
        avatar: { height: 64, width: 64, x: -252, y: -476 },
        type: constants.MONSTER.TYPE.FIEND.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SEI_RYU.KEY,
        transformationGroup: null
    }, {
        agility: 100,
        defense: 90,
        hp: 2000,
        level: 16,
        mana: 100,
        name: 'Byak-ko2',
        strength: 100,
        image: { height: 192, width: 144, x: -1293, y: -423},
        avatar: { height: 64, width: 64, x: -432, y: -476 },
        type: constants.MONSTER.TYPE.FIEND.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.BYAK_KO.KEY,
        transformationGroup: null
    }, {
        agility: 100,
        defense: 100,
        hp:  2500,
        level: 16,
        mana: 100,
        name: 'Su-zaku2',
        strength: 100,
        image: { height: 192, width: 141, x: -1488, y: -423},
        avatar: { height: 64, width: 96, x: -522, y: -476 },
        type: constants.MONSTER.TYPE.FIEND.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SU_ZAKU.KEY,
        transformationGroup: null
    }, {
        agility: 11,
        defense: 6,
        hp: 60,
        level: 2,
        mana: 5,
        name: 'Barracud',
        strength: 9,
        image: { height: 192, width: 96, x: -153, y: 0},
        avatar: { height: 32, width: 32, x: -382, y: -708 },
        type: constants.MONSTER.TYPE.FISH.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.FISH.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.FISH.KEY
    }, {
        agility: 14,
        defense: 9,
        hp: 82,
        level: 3,
        mana: 6,
        name: 'Piranha',
        strength: 11,
        image: { height: 192, width: 96, x: -153, y: 0},
        avatar: { height: 32, width: 32, x: -382, y: -708 },
        type: constants.MONSTER.TYPE.FISH.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.FISH.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.FISH.KEY
    }, {
        agility: 30,
        defense: 21,
        hp: 175,
        level: 6,
        mana: 14,
        name: 'Shark',
        strength: 23,
        image: { height: 192, width: 96, x: -153, y: 0},
        avatar: { height: 32, width: 32, x: -382, y: -708 },
        type: constants.MONSTER.TYPE.FISH.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.FISH.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.FISH.KEY
    }, {
        agility: 54,
        defense: 40,
        hp: 330,
        level: 9,
        mana: 28,
        name: 'Gunfish',
        strength: 42,
        image: { height: 192, width: 96, x: -153, y: 0},
        avatar: { height: 32, width: 32, x: -382, y: -708 },
        type: constants.MONSTER.TYPE.FISH.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.FISH.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.FISH.KEY
    }, {
        agility: 88,
        defense: 69,
        hp: 606,
        level: 13,
        mana: 52,
        name: 'Elec Eel',
        strength: 71,
        image: { height: 192, width: 96, x: -153, y: 0},
        avatar: { height: 32, width: 32, x: -382, y: -708 },
        type: constants.MONSTER.TYPE.FISH.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.FISH.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.FISH.KEY
    }, {
        agility: 99,
        defense: 80,
        hp: 729,
        level: 16,
        mana: 62,
        name: 'Leviathn',
        strength: 82,
        image: { height: 192, width: 96, x: -153, y: 0},
        avatar: { height: 32, width: 32, x: -382, y: -708 },
        type: constants.MONSTER.TYPE.FISH.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.FISH.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.FISH.KEY
    }, {
        agility: 9,
        defense: 8,
        hp: 20,
        level: 1,
        mana: 5,
        name: 'Fly',
        strength: 6,
        image: { height: 192, width: 96, x: -291, y: -192},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.FLY.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.FLY.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 18,
        defense: 17,
        hp: 82,
        level: 3,
        mana: 11,
        name: 'Dragonfly',
        strength: 12,
        image: { height: 192, width: 96, x: -291, y: -192},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.FLY.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.FLY.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 26,
        defense: 25,
        hp: 126,
        level: 5,
        mana: 17,
        name: 'Hornet',
        strength: 18,
        image: { height: 192, width: 96, x: -291, y: -192},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.FLY.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.FLY.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 31,
        defense: 30,
        hp: 150,
        level: 6,
        mana: 21,
        name: 'Mosquito',
        strength: 22,
        image: { height: 192, width: 96, x: -291, y: -192},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.FLY.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.FLY.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 89,
        defense: 88,
        hp: 551,
        level: 13,
        mana: 69,
        name: 'Cicada',
        strength: 70,
        image: { height: 192, width: 96, x: -291, y: -192},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.FLY.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.FLY.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 99,
        defense: 99,
        hp: 666,
        level: 16,
        mana: 80,
        name: 'Mantis',
        strength: 82,
        image: { height: 192, width: 96, x: -291, y: -192},
        avatar: { height: 32, width: 32, x: -2, y: -708 },
        type: constants.MONSTER.TYPE.FLY.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.FLY.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ANT_FLY_CRAB.KEY
    }, {
        agility: 8,
        defense: 3,
        hp: 20,
        level: 2,
        mana: 9,
        name: 'O-bake',
        strength: 4,
        image: { height: 192, width: 96, x: -783, y: 0},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.GHOST.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GHOST.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }, {
        agility: 14,
        defense: 5,
        hp: 82,
        level: 3,
        mana: 15,
        name: 'Phantom',
        strength: 6,
        image: { height: 192, width: 96, x: -783, y: 0},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.GHOST.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GHOST.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }, {
        agility: 54,
        defense: 27,
        hp: 295,
        level: 9,
        mana: 55,
        name: 'Buruburu',
        strength: 28,
        image: { height: 192, width: 96, x: -783, y: 0},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.GHOST.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GHOST.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }, {
        agility: 83,
        defense: 46,
        hp: 501,
        level: 12,
        mana: 84,
        name: 'Wraith',
        strength: 47,
        image: { height: 192, width: 96, x: -783, y: 0},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.GHOST.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GHOST.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }, {
        agility: 94,
        defense: 55,
        hp: 606,
        level: 13,
        mana: 95,
        name: 'Spector',
        strength: 56,
        image: { height: 192, width: 96, x: -783, y: 0},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.GHOST.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GHOST.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }, {
        agility: 99,
        defense: 61,
        hp: 666,
        level: 16,
        mana: 99,
        name: 'Ghost',
        strength: 63,
        image: { height: 192, width: 96, x: -783, y: 0},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.GHOST.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GHOST.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }, {
        agility: 4,
        defense: 6,
        hp: 20,
        level: 1,
        mana: 3,
        name: 'Goblin',
        strength: 9,
        image: { height: 192, width: 144, x: -540, y: -423},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.GOBLIN.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GOBLIN.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 7,
        defense: 9,
        hp: 60,
        level: 2,
        mana: 5,
        name: 'Oni',
        strength: 14,
        image: { height: 192, width: 144, x: -540, y: -423},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.GOBLIN.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GOBLIN.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 32,
        defense: 34,
        hp: 262,
        level: 8,
        mana: 22,
        name: 'Ogre',
        strength: 55,
        image: { height: 192, width: 144, x: -540, y: -423},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.GOBLIN.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GOBLIN.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 54,
        defense: 56,
        hp: 454,
        level: 11,
        mana: 39,
        name: 'Giant',
        strength: 87,
        image: { height: 192, width: 144, x: -540, y: -423},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.GOBLIN.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GOBLIN.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 74,
        defense: 76,
        hp: 666,
        level: 13,
        mana: 56,
        name: 'Titan',
        strength: 99,
        image: { height: 192, width: 144, x: -540, y: -423},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.GOBLIN.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GOBLIN.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 80,
        defense: 82,
        hp: 729,
        level: 16,
        mana: 62,
        name: 'Susano-o',
        strength: 99,
        image: { height: 192, width: 144, x: -540, y: -423},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.GOBLIN.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GOBLIN.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 11,
        defense: 18,
        hp: 150,
        level: 5,
        mana: 24,
        name: 'Woodman',
        strength: 26,
        image: { height: 192, width: 141, x: -1248, y: -192},
        avatar: { height: 32, width: 32, x: -192, y: -708 },
        type: constants.MONSTER.TYPE.GOLEM.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GOLEM.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOLEM.KEY
    }, {
        agility: 25,
        defense: 37,
        hp: 295,
        level: 8,
        mana: 48,
        name: 'Clayman',
        strength: 50,
        image: { height: 192, width: 141, x: -1248, y: -192},
        avatar: { height: 32, width: 32, x: -192, y: -708 },
        type: constants.MONSTER.TYPE.GOLEM.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GOLEM.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOLEM.KEY
    }, {
        agility: 28,
        defense: 41,
        hp: 330,
        level: 9,
        mana: 53,
        name: 'Stoneman',
        strength: 55,
        image: { height: 192, width: 141, x: -1248, y: -192},
        avatar: { height: 32, width: 32, x: -192, y: -708 },
        type: constants.MONSTER.TYPE.GOLEM.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GOLEM.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOLEM.KEY
    }, {
        agility: 47,
        defense: 65,
        hp: 551,
        level: 12,
        mana: 82,
        name: 'Ironman',
        strength: 84,
        image: { height: 192, width: 141, x: -1248, y: -192},
        avatar: { height: 32, width: 32, x: -192, y: -708 },
        type: constants.MONSTER.TYPE.GOLEM.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GOLEM.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOLEM.KEY
    }, {
        agility: 56,
        defense: 75,
        hp: 666,
        level: 13,
        mana: 93,
        name: 'Fireman',
        strength: 95,
        image: { height: 192, width: 141, x: -1248, y: -192},
        avatar: { height: 32, width: 32, x: -192, y: -708 },
        type: constants.MONSTER.TYPE.GOLEM.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GOLEM.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOLEM.KEY
    }, {
        agility: 62,
        defense: 81,
        hp: 729,
        level: 16,
        mana: 99,
        name: 'Mazin',
        strength: 99,
        image: { height: 192, width: 141, x: -1248, y: -192},
        avatar: { height: 32, width: 32, x: -192, y: -708 },
        type: constants.MONSTER.TYPE.GOLEM.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GOLEM.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOLEM.KEY
    }, {
        agility: 21,
        defense: 14,
        hp: 103,
        level: 4,
        mana: 22,
        name: 'Griffin',
        strength: 15,
        image: { height: 192, width: 144, x: 0, y: -423},
        avatar: { height: 32, width: 32, x: -402, y: -638 },
        type: constants.MONSTER.TYPE.GRIFFIN.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GRIFFIN.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 30,
        defense: 21,
        hp: 150,
        level: 6,
        mana: 31,
        name: 'Mantcore',
        strength: 22,
        image: { height: 192, width: 144, x: 0, y: -423},
        avatar: { height: 32, width: 32, x: -402, y: -638 },
        type: constants.MONSTER.TYPE.GRIFFIN.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GRIFFIN.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 49,
        defense: 36,
        hp: 262,
        level: 9,
        mana: 50,
        name: 'Chimera',
        strength: 37,
        image: { height: 192, width: 144, x: 0, y: -423},
        avatar: { height: 32, width: 32, x: -402, y: -638 },
        type: constants.MONSTER.TYPE.GRIFFIN.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GRIFFIN.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 71,
        defense: 54,
        hp: 409,
        level: 11,
        mana: 72,
        name: 'Nue',
        strength: 55,
        image: { height: 192, width: 144, x: 0, y: -423},
        avatar: { height: 32, width: 32, x: -402, y: -638 },
        type: constants.MONSTER.TYPE.GRIFFIN.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GRIFFIN.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 94,
        defense: 74,
        hp: 606,
        level: 13,
        mana: 95,
        name: 'Sphinx',
        strength: 75,
        image: { height: 192, width: 144, x: 0, y: -423},
        avatar: { height: 32, width: 32, x: -402, y: -638 },
        type: constants.MONSTER.TYPE.GRIFFIN.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GRIFFIN.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 99,
        defense: 80,
        hp: 666,
        level: 16,
        mana: 99,
        name: 'Ki-rin',
        strength: 82,
        image: { height: 192, width: 144, x: 0, y: -423},
        avatar: { height: 32, width: 32, x: -402, y: -638 },
        type: constants.MONSTER.TYPE.GRIFFIN.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.GRIFFIN.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.ALBATROS_DRAGON_GRIFFIN.KEY
    }, {
        agility: 9,
        defense: 8,
        hp: 82,
        level: 3,
        mana: 12,
        name: 'Gargoyle',
        strength: 11,
        image: { height: 192, width: 144, x: -1428, y: -192},
        avatar: { height: 32, width: 32, x: -402, y: -638 },
        type: constants.MONSTER.TYPE.IMP.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.IMP.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.CONDOR_IMP.KEY
    }, {
        agility: 24,
        defense: 23,
        hp: 202,
        level: 7,
        mana: 27,
        name: 'Imp',
        strength: 26,
        image: { height: 192, width: 144, x: -1428, y: -192},
        avatar: { height: 32, width: 32, x: -402, y: -638 },
        type: constants.MONSTER.TYPE.IMP.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.IMP.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.CONDOR_IMP.KEY
    }, {
        agility: 54,
        defense: 53,
        hp: 454,
        level: 11,
        mana: 57,
        name: 'Demon',
        strength: 56,
        image: { height: 192, width: 144, x: -1428, y: -192},
        avatar: { height: 32, width: 32, x: -402, y: -638 },
        type: constants.MONSTER.TYPE.IMP.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.IMP.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.CONDOR_IMP.KEY
    }, {
        agility: 59,
        defense: 58,
        hp: 501,
        level: 12,
        mana: 62,
        name: 'Demolord',
        strength: 61,
        image: { height: 192, width: 144, x: -1428, y: -192},
        avatar: { height: 32, width: 32, x: -402, y: -638 },
        type: constants.MONSTER.TYPE.IMP.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.IMP.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.CONDOR_IMP.KEY
    }, {
        agility: 74,
        defense: 73,
        hp: 666,
        level: 13,
        mana: 77,
        name: 'Demoking',
        strength: 76,
        image: { height: 192, width: 144, x: -1428, y: -192},
        avatar: { height: 32, width: 32, x: -402, y: -638 },
        type: constants.MONSTER.TYPE.IMP.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.IMP.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.CONDOR_IMP.KEY
    }, {
        agility: 80,
        defense: 79,
        hp: 729,
        level: 16,
        mana: 83,
        name: 'Athtalot',
        strength: 82,
        image: { height: 192, width: 144, x: -1428, y: -192},
        avatar: { height: 32, width: 32, x: -402, y: -638 },
        type: constants.MONSTER.TYPE.IMP.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.IMP.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.CONDOR_IMP.KEY
    }, {
        agility: 4,
        defense: 7,
        hp: 40,
        level: 1,
        mana: 2,
        name: 'Lizard',
        strength: 5,
        image: { height: 192, width: 96, x: -1338, y: 0},
        avatar: { height: 32, width: 32, x: -992, y: -638 },
        type: constants.MONSTER.TYPE.LIZARD.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.LIZARD.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.BULL_LIZARD.KEY
    }, {
        agility: 6,
        defense: 11,
        hp: 82,
        level: 2,
        mana: 4,
        name: 'P-frog',
        strength: 8,
        image: { height: 192, width: 96, x: -1338, y: 0},
        avatar: { height: 32, width: 32, x: -992, y: -638 },
        type: constants.MONSTER.TYPE.LIZARD.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.LIZARD.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.BULL_LIZARD.KEY
    }, {
        agility: 7,
        defense: 14,
        hp: 103,
        level: 3,
        mana: 5,
        name: 'Gecko',
        strength: 12,
        image: { height: 192, width: 96, x: -1338, y: 0},
        avatar: { height: 32, width: 32, x: -992, y: -638 },
        type: constants.MONSTER.TYPE.LIZARD.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.LIZARD.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.BULL_LIZARD.KEY
    }, {
        agility: 40,
        defense: 71,
        hp: 501,
        level: 11,
        mana: 38,
        name: 'Dinosaur',
        strength: 55,
        image: { height: 192, width: 96, x: -1338, y: 0},
        avatar: { height: 32, width: 32, x: -992, y: -638 },
        type: constants.MONSTER.TYPE.LIZARD.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.LIZARD.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.BULL_LIZARD.KEY
    }, {
        agility: 53,
        defense: 88,
        hp: 666,
        level: 13,
        mana: 51,
        name: 'Salamand',
        strength: 70,
        image: { height: 192, width: 96, x: -1338, y: 0},
        avatar: { height: 32, width: 32, x: -992, y: -638 },
        type: constants.MONSTER.TYPE.LIZARD.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.LIZARD.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.BULL_LIZARD.KEY
    }, {
        agility: 63,
        defense: 99,
        hp: 795,
        level: 16,
        mana: 61,
        name: 'Basilisk',
        strength: 81,
        image: { height: 192, width: 96, x: -1338, y: 0},
        avatar: { height: 32, width: 32, x: -992, y: -638 },
        type: constants.MONSTER.TYPE.LIZARD.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.LIZARD.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.BULL_LIZARD.KEY
    }, {
        agility: 19,
        defense: 17,
        hp: 126,
        level: 5,
        mana: 25,
        name: 'Medusa',
        strength: 11,
        image: { height: 192, width: 96, x: -918, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.MEDUSA.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.MEDUSA.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 23,
        defense: 21,
        hp: 150,
        level: 6,
        mana: 30,
        name: 'Siren',
        strength: 14,
        image: { height: 192, width: 96, x: -918, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.MEDUSA.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.MEDUSA.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 56,
        defense: 54,
        hp: 409,
        level: 11,
        mana: 71,
        name: 'Lamia',
        strength: 39,
        image: { height: 192, width: 96, x: -918, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.MEDUSA.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.MEDUSA.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 61,
        defense: 59,
        hp: 454,
        level: 12,
        mana: 77,
        name: 'Naga',
        strength: 43,
        image: { height: 192, width: 96, x: -918, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.MEDUSA.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.MEDUSA.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 76,
        defense: 74,
        hp: 606,
        level: 13,
        mana: 94,
        name: 'Scylla',
        strength: 56,
        image: { height: 192, width: 96, x: -918, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.MEDUSA.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.MEDUSA.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 82,
        defense: 80,
        hp: 666,
        level: 16,
        mana: 99,
        name: 'Lilith',
        strength: 62,
        image: { height: 192, width: 96, x: -918, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.MEDUSA.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.MEDUSA.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 8,
        defense: 16,
        hp: 150,
        level: 4,
        mana: 9,
        name: 'Cactus',
        strength: 15,
        image: { height: 192, width: 96, x: -1485, y: 0},
        avatar: { height: 32, width: 32, x: -592, y: -638 },
        type: constants.MONSTER.TYPE.PLANT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.PLANT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.PLANT_SEA.KEY
    }, {
        agility: 10,
        defense: 19,
        hp: 175,
        level: 5,
        mana: 11,
        name: 'P-flower',
        strength: 18,
        image: { height: 192, width: 96, x: -1485, y: 0},
        avatar: { height: 32, width: 32, x: -592, y: -638 },
        type: constants.MONSTER.TYPE.PLANT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.PLANT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.PLANT_SEA.KEY
    }, {
        agility: 15,
        defense: 26,
        hp: 231,
        level: 7,
        mana: 16,
        name: 'Garlic',
        strength: 25,
        image: { height: 192, width: 96, x: -1485, y: 0},
        avatar: { height: 32, width: 32, x: -592, y: -638 },
        type: constants.MONSTER.TYPE.PLANT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.PLANT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.PLANT_SEA.KEY
    }, {
        agility: 27,
        defense: 42,
        hp: 368,
        level: 9,
        mana: 28,
        name: 'Thorn',
        strength: 41,
        image: { height: 192, width: 96, x: -1485, y: 0},
        avatar: { height: 32, width: 32, x: -592, y: -638 },
        type: constants.MONSTER.TYPE.PLANT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.PLANT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.PLANT_SEA.KEY
    }, {
        agility: 51,
        defense: 71,
        hp: 666,
        level: 13,
        mana: 52,
        name: 'F-flower',
        strength: 70,
        image: { height: 192, width: 96, x: -1485, y: 0},
        avatar: { height: 32, width: 32, x: -592, y: -638 },
        type: constants.MONSTER.TYPE.PLANT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.PLANT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.PLANT_SEA.KEY
    }, {
        agility: 61,
        defense: 82,
        hp: 795,
        level: 16,
        mana: 62,
        name: 'Darkrose',
        strength: 81,
        image: { height: 192, width: 96, x: -1485, y: 0},
        avatar: { height: 32, width: 32, x: -592, y: -638 },
        type: constants.MONSTER.TYPE.PLANT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.PLANT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.PLANT_SEA.KEY
    }, {
        agility: 5,
        defense: 4,
        hp: 40,
        level: 1,
        mana: 7,
        name: 'Wererat',
        strength: 8,
        image: { height: 192, width: 96, x: -18, y: -192},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.RAT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.RAT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 11,
        defense: 7,
        hp: 103,
        level: 4,
        mana: 13,
        name: 'Werewolf',
        strength: 17,
        image: { height: 192, width: 96, x: -18, y: -192},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.RAT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.RAT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 21,
        defense: 14,
        hp: 175,
        level: 6,
        mana: 23,
        name: 'Catwoman',
        strength: 30,
        image: { height: 192, width: 96, x: -18, y: -192},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.RAT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.RAT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 54,
        defense: 39,
        hp: 454,
        level: 11,
        mana: 56,
        name: 'Minotaur',
        strength: 71,
        image: { height: 192, width: 96, x: -18, y: -192},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.RAT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.RAT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 69,
        defense: 52,
        hp: 606,
        level: 13,
        mana: 71,
        name: 'Rakshasa',
        strength: 88,
        image: { height: 192, width: 96, x: -18, y: -192},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.RAT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.RAT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 80,
        defense: 62,
        hp: 729,
        level: 16,
        mana: 82,
        name: 'Anubis',
        strength: 99,
        image: { height: 192, width: 96, x: -18, y: -192},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.RAT.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.RAT.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 12,
        defense: 11,
        hp: 126,
        level: 4,
        mana: 7,
        name: 'Octopus',
        strength: 13,
        image: { height: 192, width: 93, x: -438, y: -192},
        avatar: { height: 32, width: 32, x: -592, y: -638 },
        type: constants.MONSTER.TYPE.SEA.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SEA.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.PLANT_SEA.KEY
    }, {
        agility: 25,
        defense: 24,
        hp: 231,
        level: 6,
        mana: 16,
        name: 'Clam',
        strength: 26,
        image: { height: 192, width: 93, x: -438, y: -192},
        avatar: { height: 32, width: 32, x: -592, y: -638 },
        type: constants.MONSTER.TYPE.SEA.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SEA.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.PLANT_SEA.KEY
    }, {
        agility: 33,
        defense: 32,
        hp: 295,
        level: 8,
        mana: 22,
        name: 'Amoeba',
        strength: 34,
        image: { height: 192, width: 93, x: -438, y: -192},
        avatar: { height: 32, width: 32, x: -592, y: -638 },
        type: constants.MONSTER.TYPE.SEA.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SEA.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.PLANT_SEA.KEY
    }, {
        agility: 50,
        defense: 49,
        hp: 409,
        level: 10,
        mana: 35,
        name: 'Ammonite',
        strength: 51,
        image: { height: 192, width: 93, x: -438, y: -192},
        avatar: { height: 32, width: 32, x: -592, y: -638 },
        type: constants.MONSTER.TYPE.SEA.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SEA.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.PLANT_SEA.KEY
    }, {
        agility: 70,
        defense: 69,
        hp: 606,
        level: 13,
        mana: 52,
        name: 'Squid',
        strength: 71,
        image: { height: 192, width: 93, x: -438, y: -192},
        avatar: { height: 32, width: 32, x: -592, y: -638 },
        type: constants.MONSTER.TYPE.SEA.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SEA.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.PLANT_SEA.KEY
    }, {
        agility: 81,
        defense: 80,
        hp: 729,
        level: 16,
        mana: 62,
        name: 'Kraken',
        strength: 82,
        image: { height: 192, width: 93, x: -438, y: -192},
        avatar: { height: 32, width: 32, x: -592, y: -638 },
        type: constants.MONSTER.TYPE.SEA.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SEA.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.PLANT_SEA.KEY
    }, {
        agility: 4,
        defense: 2,
        hp: 20,
        level: 1,
        mana: 7,
        name: 'Skeleton',
        strength: 5,
        image: { height: 192, width: 96, x: -1620, y: 0},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.SKELETON.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SKELETON.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }, {
        agility: 8,
        defense: 6,
        hp: 103,
        level: 4,
        mana: 17,
        name: 'Red Bone',
        strength: 12,
        image: { height: 192, width: 96, x: -1620, y: 0},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.SKELETON.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SKELETON.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }, {
        agility: 33,
        defense: 31,
        hp: 368,
        level: 10,
        mana: 60,
        name: 'Dokuro',
        strength: 46,
        image: { height: 192, width: 96, x: -1620, y: 0},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.SKELETON.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SKELETON.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }, {
        agility: 44,
        defense: 42,
        hp: 501,
        level: 12,
        mana: 77,
        name: 'Warrior',
        strength: 60,
        image: { height: 192, width: 96, x: -1620, y: 0},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.SKELETON.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SKELETON.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }, {
        agility: 57,
        defense: 55,
        hp: 666,
        level: 13,
        mana: 94,
        name: 'Boneking',
        strength: 75,
        image: { height: 192, width: 96, x: -1620, y: 0},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.SKELETON.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SKELETON.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }, {
        agility: 63,
        defense: 61,
        hp: 729,
        level: 16,
        mana: 99,
        name: 'Lich',
        strength: 81,
        image: { height: 192, width: 96, x: -1620, y: 0},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.SKELETON.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SKELETON.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }, {
        agility: 3,
        defense: 4,
        hp: 60,
        level: 2,
        mana: 8,
        name: 'Slime',
        strength: 5,
        image: { height: 192, width: 96, x: -393, y: 0},
        avatar: { height: 32, width: 32, x: -792, y: -638 },
        type: constants.MONSTER.TYPE.SLIME.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SLIME.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.EYE_SLIME.KEY
    }, {
        agility: 21,
        defense: 22,
        hp: 295,
        level: 8,
        mana: 44,
        name: 'Jelly',
        strength: 23,
        image: { height: 192, width: 96, x: -393, y: 0},
        avatar: { height: 32, width: 32, x: -792, y: -638 },
        type: constants.MONSTER.TYPE.SLIME.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SLIME.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.EYE_SLIME.KEY
    }, {
        agility: 34,
        defense: 35,
        hp: 454,
        level: 10,
        mana: 65,
        name: 'Tororo',
        strength: 36,
        image: { height: 192, width: 96, x: -393, y: 0},
        avatar: { height: 32, width: 32, x: -792, y: -638 },
        type: constants.MONSTER.TYPE.SLIME.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SLIME.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.EYE_SLIME.KEY
    }, {
        agility: 42,
        defense: 43,
        hp: 551,
        level: 12,
        mana: 77,
        name: 'Gummy',
        strength: 44,
        image: { height: 192, width: 96, x: -393, y: 0},
        avatar: { height: 32, width: 32, x: -792, y: -638 },
        type: constants.MONSTER.TYPE.SLIME.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SLIME.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.EYE_SLIME.KEY
    }, {
        agility: 55,
        defense: 56,
        hp: 729,
        level: 13,
        mana: 94,
        name: 'Pudding',
        strength: 57,
        image: { height: 192, width: 96, x: -393, y: 0},
        avatar: { height: 32, width: 32, x: -792, y: -638 },
        type: constants.MONSTER.TYPE.SLIME.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SLIME.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.EYE_SLIME.KEY
    }, {
        agility: 61,
        defense: 62,
        hp: 795,
        level: 16,
        mana: 99,
        name: 'Hi-slime',
        strength: 63,
        image: { height: 192, width: 96, x: -393, y: 0},
        avatar: { height: 32, width: 30, x: -792, y: -638 },
        type: constants.MONSTER.TYPE.SLIME.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SLIME.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.EYE_SLIME.KEY
    }, {
        agility: 7,
        defense: 11,
        hp: 60,
        level: 2,
        mana: 5,
        name: 'Snake',
        strength: 9,
        image: { height: 192, width: 96, x: -528, y: 0},
        avatar: { height: 32, width: 30, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.SNAKE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SNAKE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 14,
        defense: 21,
        hp: 126,
        level: 5,
        mana: 9,
        name: 'Serpent',
        strength: 16,
        image: { height: 192, width: 96, x: -528, y: 0},
        avatar: { height: 32, width: 30, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.SNAKE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SNAKE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 28,
        defense: 39,
        hp: 231,
        level: 7,
        mana: 19,
        name: 'Anaconda',
        strength: 30,
        image: { height: 192, width: 96, x: -528, y: 0},
        avatar: { height: 32, width: 30, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.SNAKE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SNAKE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 49,
        defense: 65,
        hp: 409,
        level: 10,
        mana: 35,
        name: 'Hydra',
        strength: 51,
        image: { height: 192, width: 96, x: -528, y: 0},
        avatar: { height: 32, width: 30, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.SNAKE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SNAKE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 69,
        defense: 88,
        hp: 606,
        level: 13,
        mana: 52,
        name: 'Ko-run',
        strength: 71,
        image: { height: 192, width: 96, x: -528, y: 0},
        avatar: { height: 32, width: 30, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.SNAKE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SNAKE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 80,
        defense: 99,
        hp: 729,
        level: 16,
        mana: 62,
        name: 'Jorgandr',
        strength: 82,
        image: { height: 192, width: 96, x: -528, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.SNAKE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.SNAKE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 10,
        defense: 8,
        hp: 60,
        level: 2,
        mana: 5,
        name: 'Wolf',
        strength: 12,
        image: { height: 192, width: 96, x: -1203, y: 0},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.WOLF.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.WOLF.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 16,
        defense: 12,
        hp: 103,
        level: 4,
        mana: 7,
        name: 'Jaguar',
        strength: 18,
        image: { height: 192, width: 96, x: -1203, y: 0},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.WOLF.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.WOLF.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 33,
        defense: 25,
        hp: 202,
        level: 7,
        mana: 16,
        name: 'Sabercat',
        strength: 35,
        image: { height: 192, width: 96, x: -1203, y: 0},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.WOLF.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.WOLF.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 59,
        defense: 46,
        hp: 368,
        level: 10,
        mana: 32,
        name: 'Snowcat',
        strength: 61,
        image: { height: 192, width: 96, x: -1203, y: 0},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.WOLF.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.WOLF.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 87,
        defense: 70,
        hp: 606,
        level: 13,
        mana: 52,
        name: 'Blackcat',
        strength: 89,
        image: { height: 192, width: 96, x: -1203, y: 0},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.WOLF.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.WOLF.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 99,
        defense: 81,
        hp: 729,
        level: 16,
        mana: 62,
        name: 'Fenswolf',
        strength: 99,
        image: { height: 192, width: 96, x: -1203, y: 0},
        avatar: { height: 32, width: 32, x: -1002, y: -578 },
        type: constants.MONSTER.TYPE.WOLF.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.WOLF.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GOBLIN_RAT_WOLF.KEY
    }, {
        agility: 4,
        defense: 5,
        hp: 82,
        level: 2,
        mana: 8,
        name: 'Worm',
        strength: 9,
        image: { height: 192, width: 84, x: -663, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.WORM.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.WORM.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 15,
        defense: 16,
        hp: 231,
        level: 7,
        mana: 25,
        name: 'P-worm',
        strength: 26,
        image: { height: 192, width: 84, x: -663, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.WORM.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.WORM.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 24,
        defense: 25,
        hp: 330,
        level: 8,
        mana: 37,
        name: 'Crawler',
        strength: 38,
        image: { height: 192, width: 84, x: -663, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.WORM.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.WORM.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 34,
        defense: 35,
        hp: 454,
        level: 10,
        mana: 50,
        name: 'Lavaworm',
        strength: 51,
        image: { height: 192, width: 84, x: -663, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.WORM.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.WORM.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 51,
        defense: 52,
        hp: 666,
        level: 13,
        mana: 70,
        name: 'Sandworm',
        strength: 71,
        image: { height: 192, width: 84, x: -663, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.WORM.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.WORM.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 61,
        defense: 62,
        hp: 795,
        level: 16,
        mana: 61,
        name: 'Gigaworm',
        strength: 82,
        image: { height: 192, width: 84, x: -663, y: 0},
        avatar: { height: 32, width: 32, x: -2, y: -638 },
        type: constants.MONSTER.TYPE.WORM.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.WORM.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.MEDUSA_SNAKE_WORM.KEY
    }, {
        agility: 3,
        defense: 4,
        hp: 60,
        level: 1,
        mana: 6,
        name: 'Zombie',
        strength: 9,
        image: { height: 192, width: 84, x: -585, y: -192},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.ZOMBIE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ZOMBIE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }, {
        agility: 5,
        defense: 6,
        hp: 103,
        level: 3,
        mana: 6,
        name: 'Ghoul',
        strength: 15,
        image: { height: 192, width: 84, x: -585, y: -192},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.ZOMBIE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ZOMBIE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }, {
        agility: 24,
        defense: 25,
        hp: 330,
        level: 9,
        mana: 37,
        name: 'Mou-jya',
        strength: 50,
        image: { height: 192, width: 84, x: -585, y: -192},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.ZOMBIE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ZOMBIE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }, {
        agility: 46,
        defense: 47,
        hp: 606,
        level: 12,
        mana: 65,
        name: 'Wight',
        strength: 84,
        image: { height: 192, width: 84, x: -585, y: -192},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.ZOMBIE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ZOMBIE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }, {
        agility: 55,
        defense: 56,
        hp: 729,
        level: 13,
        mana: 75,
        name: 'Ghast',
        strength: 95,
        image: { height: 192, width: 84, x: -585, y: -192},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.ZOMBIE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ZOMBIE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }, {
        agility: 61,
        defense: 62,
        hp: 795,
        level: 16,
        mana: 82,
        name: 'Revnant',
        strength: 99,
        image: { height: 192, width: 84, x: -585, y: -192},
        avatar: { height: 32, width: 32, x: -802, y: -578 },
        type: constants.MONSTER.TYPE.ZOMBIE.KEY,
        transformationType: constants.MONSTER.TRANSFORMATION_TYPE.ZOMBIE.KEY,
        transformationGroup: constants.MONSTER.TRANSFORMATION_GROUP.GHOST_SKELETON_ZOMBIE.KEY
    }
];